# In .github/workflows/deploy.yml

name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Trigger this action on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a recent LTS version of Node.js

      - name: Install dependencies
        run: cd frontend && npm install # Go into the frontend folder and install

      - name: Build the project
        run: cd frontend && npm run build # Go into the frontend folder and build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist # The folder that the build command generates